version: 0.2

phases:
    install:
        commands:
            - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
            - sudo dpkg --force-all -i libstdc++6
            - wget -q https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_extended_0.53_Linux-64bit.deb
            - dpkg -i hugo_extended_0.53_Linux-64bit.deb
    build:
        commands:
            - echo "Building web site"
            - hugo
    post_build:
        commands:
            - echo "Invalidating CloudFront cache"
            - aws cloudfront create-invalidation --distribution-id E39L96LWBSWYC8 --paths /*.html /images/**/* /js/* /css/*
artifacts:
    files:
      - '**/*'
    base-directory: 'public'
